'use strict';

// Central error-code catalogue. All `runtime.error(<code>, ...)` calls SHOULD
// reference one of these constants so the surface stays in sync with
// `docs/error-codes.md`. The errorCodes.drift.test.js test fails CI if a new
// literal appears in src/ without being added here.

const ErrorCodes = Object.freeze({
  // Generic / transport
  UNHANDLED: 'UNHANDLED',
  PAYLOAD_PARSE_ERROR: 'PAYLOAD_PARSE_ERROR',
  TENANT_NOT_AUTHORIZED: 'TENANT_NOT_AUTHORIZED',
  PATH_NOT_FOUND: 'PATH_NOT_FOUND',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  RATE_LIMITED: 'RATE_LIMITED',
  REQUEST_TIMEOUT: 'REQUEST_TIMEOUT',
  METRICS_UNAUTHORIZED: 'METRICS_UNAUTHORIZED',
  DATE_RANGE_INVALID: 'DATE_RANGE_INVALID',
  DEVICE_MISMATCH: 'DEVICE_MISMATCH',

  // Identity / auth
  LOGIN_INVALID_CREDENTIALS: 'LOGIN_INVALID_CREDENTIALS',
  LOGIN_RATE_LIMITED: 'LOGIN_RATE_LIMITED',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED',
  REFRESH_TOKEN_REUSED: 'REFRESH_TOKEN_REUSED',
  MFA_REQUIRED: 'MFA_REQUIRED',
  MFA_INVALID: 'MFA_INVALID',
  MFA_ALREADY_ENROLLED: 'MFA_ALREADY_ENROLLED',
  USER_INVALID: 'USER_INVALID',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_EMAIL_DUPLICATE: 'USER_EMAIL_DUPLICATE',
  ROLE_GRANT_FORBIDDEN: 'ROLE_GRANT_FORBIDDEN',
  STORE_INVALID: 'STORE_INVALID',

  // Subscription / billing ledger
  SUBSCRIPTION_PLAN_INVALID: 'SUBSCRIPTION_PLAN_INVALID',
  SUBSCRIPTION_STATE_INVALID: 'SUBSCRIPTION_STATE_INVALID',
  SUBSCRIPTION_IDEMPOTENCY_CONFLICT: 'SUBSCRIPTION_IDEMPOTENCY_CONFLICT',
  SUBSCRIPTION_FEATURE_NOT_INCLUDED: 'SUBSCRIPTION_FEATURE_NOT_INCLUDED',
  SUBSCRIPTION_LIMIT_EXCEEDED: 'SUBSCRIPTION_LIMIT_EXCEEDED',

  // Catalog
  MODIFIER_RULE_INVALID: 'MODIFIER_RULE_INVALID',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  PRICE_OUT_OF_RANGE: 'PRICE_OUT_OF_RANGE',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_NAME_DUPLICATE: 'PRODUCT_NAME_DUPLICATE',
  CATALOG_IDEMPOTENCY_CONFLICT: 'CATALOG_IDEMPOTENCY_CONFLICT',
  PUBLISH_CONFLICT: 'PUBLISH_CONFLICT',
  IMPORT_PAYLOAD_INVALID: 'IMPORT_PAYLOAD_INVALID',

  // Commerce
  ORDER_ITEM_INVALID: 'ORDER_ITEM_INVALID',
  IDEMPOTENCY_KEY_MISMATCH: 'IDEMPOTENCY_KEY_MISMATCH',
  ORDER_IDEMPOTENCY_CONFLICT: 'ORDER_IDEMPOTENCY_CONFLICT',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_STATE_INVALID: 'ORDER_STATE_INVALID',
  DISCOUNT_INVALID: 'DISCOUNT_INVALID',
  PAYMENT_INVALID: 'PAYMENT_INVALID',
  PAYMENT_DECLINED: 'PAYMENT_DECLINED',
  OUT_OF_STOCK: 'OUT_OF_STOCK',
  REFUND_AMOUNT_INVALID: 'REFUND_AMOUNT_INVALID',
  VOID_NOT_ALLOWED: 'VOID_NOT_ALLOWED',
  RESTOCK_NEGATIVE_BLOCKED: 'RESTOCK_NEGATIVE_BLOCKED',

  // Operations / channels / inventory
  SOURCE_CHANNEL_UNKNOWN: 'SOURCE_CHANNEL_UNKNOWN',
  ORDER_SOURCE_DUPLICATE: 'ORDER_SOURCE_DUPLICATE',
  MISSING_REFERENCE_ID: 'MISSING_REFERENCE_ID',
  SOURCE_DUPLICATE: 'SOURCE_DUPLICATE',
  CHANNEL_AUTH_FAILED: 'CHANNEL_AUTH_FAILED',
  CHANNEL_IDEMPOTENCY_CONFLICT: 'CHANNEL_IDEMPOTENCY_CONFLICT',
  PAYMENT_UNKNOWN: 'PAYMENT_UNKNOWN',
  SOURCE_ITEM_CLOSED: 'SOURCE_ITEM_CLOSED',
  KDS_STATE_INVALID: 'KDS_STATE_INVALID',
  KDS_TRANSITION_INVALID: 'KDS_TRANSITION_INVALID',
  CASHBOX_ALREADY_OPEN: 'CASHBOX_ALREADY_OPEN',
  CASH_SHORTFALL: 'CASH_SHORTFALL',
  CASH_SHORTFALL_UNEXPLAINED: 'CASH_SHORTFALL_UNEXPLAINED',
  DRAWER_NOT_FOUND: 'DRAWER_NOT_FOUND',
  INVENTORY_ADJUSTMENT_INVALID: 'INVENTORY_ADJUSTMENT_INVALID',
  INVENTORY_NEGATIVE_AFTER_MOVE: 'INVENTORY_NEGATIVE_AFTER_MOVE',
  INVENTORY_LEDGER_WRITE_FAILED: 'INVENTORY_LEDGER_WRITE_FAILED',
  STOCK_COUNT_INVALID: 'STOCK_COUNT_INVALID',
  TRANSFER_INVALID: 'TRANSFER_INVALID',
  COUPON_NOT_APPLICABLE: 'COUPON_NOT_APPLICABLE',
  CUSTOMER_PHONE_INVALID: 'CUSTOMER_PHONE_INVALID',
  CUSTOMER_QUERY_TOO_SHORT: 'CUSTOMER_QUERY_TOO_SHORT',
  POINTS_INVALID: 'POINTS_INVALID',

  // Risk / invoices / reports / printing
  INVOICE_ORDER_NOT_READY: 'INVOICE_ORDER_NOT_READY',
  INVOICE_NOT_FOUND: 'INVOICE_NOT_FOUND',
  INVOICE_VOID_INVALID: 'INVOICE_VOID_INVALID',
  INVOICE_AMOUNT_MISMATCH: 'INVOICE_AMOUNT_MISMATCH',
  INVOICE_UPLOAD_TIMEOUT: 'INVOICE_UPLOAD_TIMEOUT',
  INVOICE_UPLOAD_FAILED: 'INVOICE_UPLOAD_FAILED',
  INVOICE_SIGNATURE_INVALID: 'INVOICE_SIGNATURE_INVALID',
  INVOICE_FSM_VIOLATION: 'INVOICE_FSM_VIOLATION',
  EXPORT_RANGE_INVALID: 'EXPORT_RANGE_INVALID',
  EXPORT_RANGE_TOO_LARGE: 'EXPORT_RANGE_TOO_LARGE',
  FILE_EXPIRED: 'FILE_EXPIRED',
  PRINTER_OFFLINE: 'PRINTER_OFFLINE',
  PRINT_JOB_NOT_RETRYABLE: 'PRINT_JOB_NOT_RETRYABLE',
  PRINT_JOB_STATE_INVALID: 'PRINT_JOB_STATE_INVALID',
  RECONCILIATION_STORE_SCOPE_VIOLATION: 'RECONCILIATION_STORE_SCOPE_VIOLATION',
  TRANSFER_STORE_SCOPE_VIOLATION: 'TRANSFER_STORE_SCOPE_VIOLATION',
  TENANT_SCOPE_VIOLATION: 'TENANT_SCOPE_VIOLATION',
  VOID_REASON_INVALID: 'VOID_REASON_INVALID',
  AI_INSIGHT_NOT_FOUND: 'AI_INSIGHT_NOT_FOUND',

  // Sync / outbox
  RETRY_LIMIT_EXCEEDED: 'RETRY_LIMIT_EXCEEDED',
  SYNC_STALE: 'SYNC_STALE',
  SYNC_JOB_NOT_FOUND: 'SYNC_JOB_NOT_FOUND',
  SYNC_RESOLUTION_INVALID: 'SYNC_RESOLUTION_INVALID',
});

module.exports = ErrorCodes;
